on:
  #push:
  workflow_dispatch:
  # Run at 9:23pm Monday-Friday
  schedule: [{cron: '0 0 1 1 1'}]

name: scrape

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    #- name: Fetch latest data
    #  run: Rscript 2-news-shiny.R

    - name: Collapse into yearly parquet files
      run: Rscript collapse.R
